{{- if .Values.traefik.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "kavita-reader.fullname" . }}
  labels:
    {{- include "kavita-reader.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.traefik.dns }}`)
      kind: Rule
      {{- if .Values.traefik.auth.enabled }}
      middlewares:
        - name: "{{ include "kavita-reader.fullname" . }}-basicauth"
      {{- end}}      
      services:
        - name: {{ include "kavita-reader.fullname" . }}
          port: {{ .Values.service.port }}
  tls:
    secretName: "{{ .Values.traefik.dns | replace "." "-" }}-tls"
{{- if .Values.traefik.auth.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "kavita-reader.fullname" . }}-auth"
  labels:
    {{- include "kavita-reader.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{.Values.traefik.auth.username }}
  password: {{.Values.traefik.auth.password }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name:  "{{ include "kavita-reader.fullname" . }}-basicauth"
  labels:
    {{- include "kavita-reader.labels" . | nindent 4 }}
spec:
  basicAuth:
    removeHeader: true
    secret: "{{ include "kavita-reader.fullname" . }}-auth"
{{- end}}    
{{- end}}
---