{{- range $key, $value := .Values.services }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "cert-{{ $value.dns | replace "." "-" }}"
spec:
  secretName: "{{ $value.dns | replace "." "-" }}-tls"
  issuerRef:
    name: {{ default "letsencrypt-prod" $value.certIssuer }}
    kind: ClusterIssuer
  commonName: {{ $value.dns | quote }}
  dnsNames:
    - {{ $value.dns | quote  }}
---
{{- end}}