{{- range $key, $value := .Values.services }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $value.serviceName }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ $value.dns }}`)
      kind: Rule
      {{- if $value.auth.enabled }}
      middlewares:
        - name: "{{ $value.serviceName }}-basicauth"
      {{- end}}
      services:
        - name: {{ $value.serviceName }}
          port: {{ $value.port }}
  tls:
    secretName: "{{ $value.dns | replace "." "-" }}-tls"
{{- if $value.auth.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $value.serviceName }}-auth"
type: kubernetes.io/basic-auth
data:
  username: {{$value.auth.username}}
  password: {{$value.auth.password}}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name:  "{{ $value.serviceName }}-basicauth"
spec:
  basicAuth:
    removeHeader: true
    secret: "{{ $value.serviceName }}-auth"
{{- end}}    
{{- end}}
---
